# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#
 
# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane
 
default_platform(:ios)
 
platform :ios do
  desc "Description of what the lane does"
  lane :CI do
      run_tests(project: "Countries.xcodeproj",
      devices: ["iPhone 6s"],
      scheme: "Countries")
  end
 
  lane :CD do |values|
 
    gym(scheme: 'Countries', project: "Countries.xcodeproj", clean: true, silent: true, include_bitcode: true, export_method: 'ad-hoc')
 
    emails = values[:'[mohinimehetre@gmail.com]'] ? values[:'[aditi.desai@silicus.com]'] : ['[mohini.mehetre@silicus.com]'] # You can list more emails here
    groups = values[:test_email] ? nil : nil # You can define groups on the web and reference them here
 
    crashlytics(api_token: '[fcba342ff395208af16975b33ace3353cc1e8101]',
             build_secret: '[31affa473c273f445881bbe3ce2e37424f3d2a5b3c0cf9e276107c97c06095ad]',
                   emails: emails,
                   groups: groups,
                    notes: 'Distributed with fastlane', # Check out the changelog_from_git_commits action
            notifications: true) # Should this distribution notify your testers via email?
 
    end
end